# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 7.0

install:
  - composer install

script: phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
